name: head_ladder
description: "Корпоративный портал для заказа внутренних услуг."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' # Стандартное ограничение для совместимости с последними версиями Flutter

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1 
  flutter_svg: ^2.0.7


  collection: ^1.19.1
  # --- Пакеты для работы приложения ---

  # Для загрузки конфигурации из .env файла (URL, токены)
  flutter_dotenv: ^5.1.0

  # Для выполнения HTTP-запросов к API
  http: ^1.2.1

  # Для локального хранения простых данных (например, настроек)
  shared_preferences: ^2.2.3

  # Для форматирования дат и чисел
  intl: ^0.19.0
  
  # Стандартные иконки в стиле iOS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Рекомендуемый набор правил для анализатора кода Dart
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # --- Регистрация ассетов (ресурсов) приложения ---
  assets:
    # КРИТИЧЕСКИ ВАЖНО: Добавляем .env файл, чтобы приложение могло его прочитать
    - .env 

    # Папки с изображениями и иконками
    - assets/images/
    - assets/icons/
    - assets/launcher_icon/

flutter_launcher_icons:
  android: "launcher_icon" # Имя иконки по умолчанию
  ios: true
  image_path: "assets/launcher_icon/icon.png" # <-- УКАЖИТЕ ПУТЬ К ВАШЕЙ ИКОНКЕ
  min_sdk_android: 21